version: '3.7'
services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'test_database'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'qwerty'
      MYSQL_ROOT_PASSWORD: 'qwerty'
    restart: always
    volumes:
      - db_django:/var/lib/mysql
  web:
    build: ./users_srv
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./users_srv/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./users_srv/.env.dev
    depends_on:
      - db

volumes:
  db_django: