version: '3.7'
services:
  web:
    build:
      context: ./users_srv
      dockerfile: Dockerfile.prod
    command: gunicorn users_srv.wsgi:application --bind 0.0.0.0:8000 --log-level debug
    volumes:
      - static_volume:/home/emphasoft_test/users_srv/static
    expose:
      - 8000
    env_file:
      - ./users_srv/.env.prod
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - db_django:/var/lib/mysql
    env_file:
      - ./users_srv/.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/emphasoft_test/users_srv/static
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  db_django:
  static_volume: