name: Run linters and unit tests

on:
  push:
    branches: [ develop ]
  pull_request:
      branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install python modules
      run: sudo apt install -y --no-install-recommends python3-venv python3-setuptools
    - name: Install pip packages
      run: |
        python3 -m venv .venv
        .venv/bin/pip install mypy flake8 django-stubs djangorestframework-stubs
    - name: Run flake8
      run: .venv/bin/python -m flake8 users_srv/
    - name: Run mypy
      run: .venv/bin/python -m mypy users_srv/
    - name: Build the docker-compose stack
      run: docker-compose up -d --build
    - name: Sleep
      uses: jakejarvis/wait-action@master
      with:
        time: '10s'
    - name: Check running containers
      run: docker ps -a
    - name: Run test suite
      run: docker-compose exec -T web python manage.py test